logging:
  pattern.console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] [%logger{20}] - %msg%n"
  level.root: info
server.error:.include-message: always
spring.data.mongodb:
  database: demo
  host: localhost
  port: 27017
kafka:
  bootstrap-servers: localhost:9092
  consumer-client-id: clientId
  consumer-group-id: groupId
  default-topic: topic