spring.data.mongodb:
  database: demo
  host: localhost
  port: 27017
logging:
  pattern.console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] [%logger{20}] - %msg%n"
  level.root: info
server.error:.include-message: always